name: Firebase Continuous Deployment

on:
  push:
    branches: [ main ]


jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - run: npm ci
      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          projects: host
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}