name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev

jobs:
  build_and_deploy_development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build applications
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
          args: '--configuration="development"'
      - name: Deploy application to Firebase [DEVELOPMENT]
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_COMMUNITY_UA }}'
          channelId: live
          projectId: dev-acua
