name: Node Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  pull_request_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint applications
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint
          all: 'true'
      - name: Test applications
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: test
          all: 'true'
      - name: Build applications
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
